### ISSUE TITLE
programatically add users to the github repo

### ISSUE THREAD

**Issue by BrianJenney** [CodeCoachJS/js_pro_main_site#5]
When a customer purchases a subscription they should be automatically added to the CodeCoach organization

The first step to achieving this is creating a new API endpoint that accepts a user email.

This is the URL for invitations https://api.github.com/orgs/CodeCoachJS/api/memberships

This API will accept an email in the payload `{"email" : " user@gmail.com"}`

This API will add a user to the codecoach org by email and should require a key to be present in the header OR whitelisting certain domains in production mode so that ONLY certain urls can request a user to be added. This can be configured via environment variable

**Comment by vazquezea96** [comment]
Would like to give this a shot!
