### ISSUE TITLE
test out local dev docs for supabase

### ISSUE THREAD

**Issue by BrianJenney** [CodeCoachJS/js_pro_main_site#8]
_good first issue to pick up_

check out this branch/PR:

https://github.com/CodeCoachJS/js_pro_main_site/pull/7

Try to get the local DB running following the instructions. Are you able to? Good - the docs work!

Is it confusing? Make the appropriate changes or document your issues in a video and work with @BrianJenney to get them fixed.

**Comment by vazquezea96** [comment]
I would like to tackle this!

**Comment by BrianJenney** [comment]
Thanks for verifying! Big step in making this more open source-y so sensitive data isn't needed to be shared
